"""Emit the ESP32's flashable identity as a C header.

Reads the device secret and the server public key that `make enroll` produced
and writes firmware/sketch_pqc/keys.h. The secret key ends up in the header, so
the header is gitignored -- exactly like flashing a key into a real board at
commissioning.

    python -m scripts.emit_firmware_keys            # device esp32-01
    DEVICE_ID=esp32-02 python -m scripts.emit_firmware_keys
"""

import os
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
KEYS = ROOT / "identities"
DEVICE_ID = os.environ.get("DEVICE_ID", "esp32-01")
OUT = ROOT / "firmware" / "sketch_pqc" / "keys.h"


def c_array(name, data):
    body = ",".join(str(b) for b in data)
    return f"static const uint8_t {name}[{len(data)}] = {{{body}}};\n"


def main():
    sk = KEYS / f"{DEVICE_ID}.key"
    pub = KEYS / "server.pub"
    if not sk.exists() or not pub.exists():
        print(f"Missing {sk} or {pub}. Run: make enroll", file=sys.stderr)
        return 1
    OUT.write_text(
        "// GENERATED by scripts/emit_firmware_keys.py — do not commit (holds a secret key).\n"
        f'#pragma once\n#define DEVICE_ID "{DEVICE_ID}"\n'
        + c_array("DEVICE_SECRET", sk.read_bytes())
        + c_array("SERVER_PUBLIC", pub.read_bytes())
    )
    print(f"Wrote {OUT} for {DEVICE_ID} "
          f"(device secret {sk.stat().st_size} B, server public {pub.stat().st_size} B)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
